### ISSUE TITLE
No effects on maps other than the first.

### ISSUE THREAD

**Issue by monteiroelias** [sogladev/mod-reset-raid-cooldowns#7]
### Current Behaviour

ModResetRaidCooldowns.MapIdEnableSettings = "533, 615, 616, 603, 649, 631, 724"

only in the first ID the cooldowns are reseted

### Expected Behaviour

on any of the maps (instances) listed in "MadrId Enable Settings" the cooldowns should be reset.

### Steps to reproduce the problem

1. Go on any other map ( 615, 616, 603, 649, 631, 724) 
2. kill any boss

### AC rev. hash/commit

last release

### Operating system

Window server

**Comment by sogladev** [comment]
Thanks for reporting this issue. I'll have a look at what's going wrong. 

~~I'll assume you're only using the LUA implementation~~ nvm, settings apply to cpp
